<form action="<?php echo $block->getUrl('magenest/magenestdirector/save'); ?>" class="form-inline" method="post"
      enctype="multipart/form-data" novalidate>
    <div class="col-m-4">
        <fieldset class="fieldset admin__fieldset " id="theme">

            <div class="admin__field field ">
                <label class="label admin__field-label" for="test_input">
                    <span>Name</span></label>
                <div class="admin__field-control control">
                    <input name="name" id="name"
                           value="" title="name" type="text" class="input-textadmin__control-text"/>
                </div>
            </div>
            <div class="form-group text-center">
                <button type="submit" class="btn btn-xs btn-success">
                    <i class="fa fa-save"></i> Save
                </button>
                <a href="<?php echo $block->getUrl('magenest/magenestdirector/index') ?>" class="btn btn-xs btn-danger">
                    <i class="fa fa-remove"></i> Cancel
                </a>
            </div>
        </fieldset>
    </div>

</form>